language: node_js

sudo: false
dist: trusty

git:
    depth: 3

node_js:
    - '10'

cache:
    directories:
        - node_modules
        - packages/core/node_modules
        - packages/admin-web-angular/node_modules
        - packages/carrier-mobile-ionic/node_modules
        - packages/shop-mobile-ionic/node_modules
        - packages/shop-web-angular/node_modules
        - packages/merchant-tablet-ionic/node_modules

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

before_install:
    - npm i -g npm@latest
    - npm i -g yarn@latest
    - npm i -g lerna@latest

install:
    - git clone -c core.symlinks=true --recursive --depth=3 --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
    - cd $TRAVIS_REPO_SLUG
    - git checkout -qf $TRAVIS_COMMIT
    - yarn install
    - yarn bootstrap

matrix:
    include:
        - env: PROJECT=packages/core
        - env: PROJECT=packages/admin-web-angular
        - env: PROJECT=packages/carrier-mobile-ionic
        - env: PROJECT=packages/shop-mobile-ionic
        - env: PROJECT=packages/shop-web-angular
        - env: PROJECT=packages/merchant-tablet-ionic

before_script:
    - cd $PROJECT

script:
    - yarn build
